[package]
name = "pros-sys"
version = "0.1.0"
edition = "2021"
description = "EFI for the PROS rust bindings"
keywords = [ "PROS", "Robotics", "bindings" ]
license = "MIT"
repository = "https://github.com/gavin-niederman/pros-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.65.1"
reqwest = { version = "0.11", features = ["blocking"] }
zip = "0.6.4"

[lib]
doctest = false