[package]
name = "pros"
version = "0.0.4"
edition = "2021"
description = "Rust bindings for PROS"
keywords = ["PROS", "Robotics", "bindings"]
license = "MIT"
repository = "https://github.com/gavin-niederman/pros-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.8"
pros-sys = { version = "0.1.1", path = "../pros-sys" }
errno = { version = "0.3.1", default-features = false }
libc = { version = "0.2.142", default-features = false }

[features]
lvgl = ["pros-sys/xapi"]
