[package]
name = "pros"
version = "0.0.5"
edition = "2021"
description = "Rust bindings for PROS"
keywords = ["PROS", "Robotics", "bindings"]
license = "MIT"
repository = "https://github.com/gavin-niederman/pros-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.8"
pros-sys = { version = "0.1.2", path = "../pros-sys" }
pros_derive = { path = "./pros_derive", version = "0.1.0", optional = true }

[features]
lvgl = ["pros-sys/xapi"]
derive = ["dep:pros_derive"]