[package]
name = "vexide-core"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Core functionality for vexide"
keywords = ["PROS", "Robotics", "bindings", "vex", "v5"]
categories = [
    "api-bindings",
    "no-std",
    "science::robotics",
]
repository = "https://github.com/vexide/vexide"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex-sdk = "0.9.1"
pros-sys = { version = "0.7.0", path = "../pros-sys" }
no_std_io = { version = "0.6.0", features = ["alloc"] }
snafu = { version = "0.8.0", default-features = false, features = [
    "rust_1_61",
    "unstable-core-error",
] }
spin = "0.9.8"
talc = "4.3.1"
lock_api = "0.4.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
dlmalloc = { version = "0.2.4", features = ["global"] }

[lints]
workspace = true
