[package]
name = "example"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pros = { path = "../pros" }

[build-dependencies]
reqwest = "0.11.17"
zip = "0.6.4"
