[package]
name = "pros"
version = "0.0.1"
edition = "2021"
description = "Rust bindings for PROS"
keywords = [ "PROS", "Robotics", "bindings" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.64.0"
reqwest = { version = "0.11", features = ["blocking"] }