[package]
name = "pros-sync"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "`SyncRobot` trait and macro for pros-rs"
keywords = ["PROS", "Robotics"]
categories = [
    "no-std",
    "science::robotics",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pros-core = { version = "0.1.0", path = "../pros-core" }

[lints]
workspace = true
