[build]
target = "./armv7a-vexos.json"

[target.armv7a-vexos]
# Change this to runner = "./runner.bat" if in windows.
runner = "sh runner.sh"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]