[package]
name = "pros-math"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Commonly used mathematical formulas for pros-rs"
keywords = ["PROS", "Robotics"]
categories = [
    "no-std",
    "science::robotics",
]

[dependencies]
num = { version = "0.4.1", default-features = false }
pros-core = { version = "0.1.0", path = "../pros-core" }

[lints]
workspace = true
