[package]
name = "vexide-panic"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Panic handler for pros-rs"
keywords = ["PROS", "Robotics", "vex", "v5"]
categories = [
    "no-std",
    "science::robotics",
]
repository = "https://github.com/gavin-niederman/pros-rs"
authors = [
    "pros-rs",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vexide-core = { version = "0.1.0", path = "../vexide-core" }
vexide-devices = { version = "0.1.0", path = "../vexide-devices", optional = true }
pros-sys = { version = "0.7.0", path = "../pros-sys" }

[features]
default = ["display_panics"]

display_panics = ["dep:vexide-devices"]

[lints]
workspace = true
