[package]
name = "vexide-graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics-core = { version = "0.4.0", optional = true }
slint = { version = "1.5.1", default-features = false, optional = true, features = ["compat-1-2", "unsafe-single-threaded", "libm", "renderer-software"] }
vex-sdk = "0.12.0"
vexide-async = { version = "0.1.0", path = "../vexide-async" }
vexide-core = { version = "0.1.0", path = "../vexide-core" }
vexide-devices = { version = "0.1.0", path = "../vexide-devices" }

[lints]
workspace = true

[features]
default = ["embedded-graphics", "slint"]

embedded-graphics = ["dep:embedded-graphics-core"]
slint = ["dep:slint"]
