[package]
name = "vexide-devices"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "High level device bindings for vexide"
keywords = ["PROS", "Robotics", "bindings", "vex", "v5"]
categories = [
    "api-bindings",
    "no-std",
    "science::robotics",
]
repository = "https://github.com/vexide/vexide"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vexide-core = { version = "0.1.0", path = "../vexide-core" }
vex-sdk = "0.11.0"
snafu = { version = "0.8.0", default-features = false, features = [
    "rust_1_61",
    "unstable-core-error",
] }
mint = "0.5.9"
no_std_io = { version = "0.6.0", features = ["alloc"] }
bitflags = "2.4.2"

[lints]
workspace = true

[features]
dangerous_motor_tuning = []
